apiVersion: v1
kind: Service
metadata:
  name: webapp1
  namespace: obserb-demo
spec:
  selector:
    app: webapp1
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
